/*
 * Copyright 2025 The ChaosBlade Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.alibaba.chaosblade.box.dao.mapper;

import com.alibaba.chaosblade.box.common.infrastructure.util.MybatisMapper;
import com.alibaba.chaosblade.box.dao.model.SceneAuthorizedDO;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

@MybatisMapper
public interface SceneAuthorizedMapper extends BaseMapper<SceneAuthorizedDO> {

  @Select(
      "<script>"
          + "SELECT sa.* FROM t_chaos_scene_authorized sa "
          + "INNER JOIN ("
          + "  SELECT function_id, MIN(id) as min_id "
          + "  FROM t_chaos_scene_authorized "
          + "  WHERE 1=1 "
          + "  <if test='query.searchKey != null and query.searchKey != \"\"'>"
          + "    AND (function_name LIKE CONCAT('%', #{query.searchKey}, '%') "
          + "         OR function_code LIKE CONCAT('%', #{query.searchKey}, '%')) "
          + "  </if>"
          + "  <if test='query.functionId != null and query.functionId != \"\"'>"
          + "    AND function_id = #{query.functionId} "
          + "  </if>"
          + "  <if test='query.functionIds != null and query.functionIds.size() > 0'>"
          + "    AND function_id IN "
          + "    <foreach collection='query.functionIds' item='fid' open='(' close=')' separator=','>"
          + "      #{fid}"
          + "    </foreach>"
          + "  </if>"
          + "  <if test='query.enabled != null'>"
          + "    AND enabled = #{query.enabled} "
          + "  </if>"
          + "  <if test='query.permission != null'>"
          + "    AND (permission &amp; #{query.permission}) = #{query.permission} "
          + "  </if>"
          + "  <if test='query.phase != null'>"
          + "    AND (phase &amp; #{query.phase}) &gt; 0 "
          + "  </if>"
          + "  <if test='query.source != null'>"
          + "    AND source = #{query.source} "
          + "  </if>"
          + "  <if test='query.grantFrom != null and query.grantFrom != \"\"'>"
          + "    AND grant_from = #{query.grantFrom} "
          + "  </if>"
          + "  <if test='query.supportScopeType != null'>"
          + "    <if test='query.supportScopeType == 1'>"
          + "      AND support_host = 1 "
          + "    </if>"
          + "    <if test='query.supportScopeType == 2'>"
          + "      AND support_k8s = 1 "
          + "      <if test='query.k8sResourceType != null'>"
          + "        <if test='query.k8sResourceType == 1'>"
          + "          AND (function_code LIKE 'chaos.pod-%' OR function_code LIKE 'litmuschaos.pod-%') "
          + "        </if>"
          + "        <if test='query.k8sResourceType == 2'>"
          + "          AND (function_code LIKE 'chaos.node-%' OR function_code LIKE 'litmuschaos.node-%') "
          + "        </if>"
          + "        <if test='query.k8sResourceType == 3'>"
          + "          AND (function_code LIKE 'chaos.container-%' OR function_code LIKE 'litmuschaos.container-%' OR function_code = 'chaos.pod-pod.delete') "
          + "        </if>"
          + "      </if>"
          + "    </if>"
          + "  </if>"
          + "  AND is_delete = "
          + "  <choose>"
          + "    <when test='query.isDelete == true'>1</when>"
          + "    <otherwise>0</otherwise>"
          + "  </choose>"
          + "  <if test='query.isPublic == null'>"
          + "    AND is_public = 1 "
          + "  </if>"
          + "  <if test='query.grantTo != null and query.grantTo != \"\"'>"
          + "    <if test='query.isPublic == true'>"
          + "      AND ((grant_to = #{query.grantTo} AND is_public = 0) OR is_public = 1) "
          + "    </if>"
          + "    <if test='query.isPublic != true'>"
          + "      AND grant_to = #{query.grantTo} AND is_public = 0 "
          + "    </if>"
          + "  </if>"
          + "  <if test='query.grantTo == null or query.grantTo == \"\"'>"
          + "    <if test='query.isPublic == true'>"
          + "      AND is_public = 1 "
          + "    </if>"
          + "  </if>"
          + "  GROUP BY function_id"
          + ") grouped ON sa.id = grouped.min_id AND sa.function_id = grouped.function_id "
          + "WHERE 1=1 "
          + "  <if test='query.searchKey != null and query.searchKey != \"\"'>"
          + "    AND (sa.function_name LIKE CONCAT('%', #{query.searchKey}, '%') "
          + "         OR sa.function_code LIKE CONCAT('%', #{query.searchKey}, '%')) "
          + "  </if>"
          + "  <if test='query.functionId != null and query.functionId != \"\"'>"
          + "    AND sa.function_id = #{query.functionId} "
          + "  </if>"
          + "  <if test='query.functionIds != null and query.functionIds.size() > 0'>"
          + "    AND sa.function_id IN "
          + "    <foreach collection='query.functionIds' item='fid' open='(' close=')' separator=','>"
          + "      #{fid}"
          + "    </foreach>"
          + "  </if>"
          + "  <if test='query.enabled != null'>"
          + "    AND sa.enabled = #{query.enabled} "
          + "  </if>"
          + "  <if test='query.permission != null'>"
          + "    AND (sa.permission &amp; #{query.permission}) = #{query.permission} "
          + "  </if>"
          + "  <if test='query.phase != null'>"
          + "    AND (sa.phase &amp; #{query.phase}) &gt; 0 "
          + "  </if>"
          + "  <if test='query.source != null'>"
          + "    AND sa.source = #{query.source} "
          + "  </if>"
          + "  <if test='query.grantFrom != null and query.grantFrom != \"\"'>"
          + "    AND sa.grant_from = #{query.grantFrom} "
          + "  </if>"
          + "  <if test='query.supportScopeType != null'>"
          + "    <if test='query.supportScopeType == 1'>"
          + "      AND sa.support_host = 1 "
          + "    </if>"
          + "    <if test='query.supportScopeType == 2'>"
          + "      AND sa.support_k8s = 1 "
          + "      <if test='query.k8sResourceType != null'>"
          + "        <if test='query.k8sResourceType == 1'>"
          + "          AND (sa.function_code LIKE 'chaos.pod-%' OR sa.function_code LIKE 'litmuschaos.pod-%') "
          + "        </if>"
          + "        <if test='query.k8sResourceType == 2'>"
          + "          AND (sa.function_code LIKE 'chaos.node-%' OR sa.function_code LIKE 'litmuschaos.node-%') "
          + "        </if>"
          + "        <if test='query.k8sResourceType == 3'>"
          + "          AND (sa.function_code LIKE 'chaos.container-%' OR sa.function_code LIKE 'litmuschaos.container-%' OR sa.function_code = 'chaos.pod-pod.delete') "
          + "        </if>"
          + "      </if>"
          + "    </if>"
          + "  </if>"
          + "  AND sa.is_delete = "
          + "  <choose>"
          + "    <when test='query.isDelete == true'>1</when>"
          + "    <otherwise>0</otherwise>"
          + "  </choose>"
          + "  <if test='query.isPublic == null'>"
          + "    AND sa.is_public = 1 "
          + "  </if>"
          + "  <if test='query.grantTo != null and query.grantTo != \"\"'>"
          + "    <if test='query.isPublic == true'>"
          + "      AND ((sa.grant_to = #{query.grantTo} AND sa.is_public = 0) OR sa.is_public = 1) "
          + "    </if>"
          + "    <if test='query.isPublic != true'>"
          + "      AND sa.grant_to = #{query.grantTo} AND sa.is_public = 0 "
          + "    </if>"
          + "  </if>"
          + "  <if test='query.grantTo == null or query.grantTo == \"\"'>"
          + "    <if test='query.isPublic == true'>"
          + "      AND sa.is_public = 1 "
          + "    </if>"
          + "  </if>"
          + "ORDER BY sa.function_create_time DESC"
          + "</script>")
  List<SceneAuthorizedDO> selectAuthorizedRecordsGroupBy(
      @Param("query")
          com.alibaba.chaosblade.box.common.infrastructure.domain.scene.SceneAuthorizedQueryRequest
              query);
}
